# templates/adder-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: adder-service
spec:
  selector:
    app: adder-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: ClusterIP
