# templates/coordinator-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: coordinator-service
spec:
  selector:
    app: coordinator-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
